=== mybatis/generator/core/mybatis-generator-core/src/main/resources/org/mybatis/generator/config/xml/mybatis-generator-config_1_0.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2006-2026 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!--
  This DTD defines the structure of the MyBatis generator configuration file.
  Configuration files should declare the DOCTYPE as follows:
  
  <!DOCTYPE generatorConfiguration PUBLIC
    "-//mybatis.org//DTD MyBatis Generator Configuration 1.0//EN"
    "https://mybatis.org/dtd/mybatis-generator-config_1_0.dtd">
  
  Please see the documentation included with MyBatis generator for details on each option
  in the DTD.  You may also view documentation on-line here:
  
  https://www.mybatis.org/generator/
  
-->

<!--
  The generatorConfiguration element is the root element for configurations.
-->
<!ELEMENT generatorConfiguration (properties?, indentationConfiguration?, javaMergeConfiguration?, classPathEntry*, context+)>

<!--
  The properties element is used to define a standard Java properties file
  that contains placeholders for use in the remainder of the configuration
  file.
-->
<!ELEMENT properties EMPTY>
<!ATTLIST properties
  resource CDATA #IMPLIED
  url CDATA #IMPLIED>

<!ELEMENT indentationConfiguration EMPTY>
<!ATTLIST indentationConfiguration
  javaIndentType CDATA #IMPLIED
  javaIndentAmount CDATA #IMPLIED
  xmlIndentType CDATA #IMPLIED
  xmlIndentAmount CDATA #IMPLIED>

<!ELEMENT javaMergeConfiguration EMPTY>
<!ATTLIST javaMergeConfiguration
  lexicalPreserving CDATA #IMPLIED
  importSortStrategy CDATA #IMPLIED
  mergeStrategy CDATA #IMPLIED>

<!--
  The context element is used to describe a context for generating files, and the source
  tables.
-->
<!ELEMENT context (property*, plugin*, commentGenerator?, (connectionFactory | jdbcConnection),
    javaTypeResolver?, (modelGenerator | javaModelGenerator), sqlMapGenerator?,
    (clientGenerator | javaClientGenerator)?, table+)>
<!ATTLIST context id ID #REQUIRED
  defaultModelType CDATA #IMPLIED
  targetRuntime CDATA #IMPLIED
  introspectedColumnImpl CDATA #IMPLIED>

<!--
  The connectionFactory element is used to describe the connection factory used
  for connecting to the database for introspection.  Either connectionFactory
  or jdbcConnection must be specified, but not both.
-->
<!ELEMENT connectionFactory (property*)>
<!ATTLIST connectionFactory
  type CDATA #IMPLIED>

<!--
  The jdbcConnection element is used to describe the JDBC connection that the generator
  will use to introspect the database.
-->
<!ELEMENT jdbcConnection (property*)>
<!ATTLIST jdbcConnection 
  driverClass CDATA #REQUIRED
  connectionURL CDATA #REQUIRED
  userId CDATA #IMPLIED
  password CDATA #IMPLIED>

<!--
  The classPathEntry element is used to add the JDBC driver to the run-time classpath.
  Repeat this element as often as needed to add elements to the classpath.
-->
<!ELEMENT classPathEntry EMPTY>
<!ATTLIST classPathEntry
  location CDATA #REQUIRED>

<!--
  The property element is used to add custom properties to many of the generator's
  configuration elements.  See each element for example properties.
  Repeat this element as often as needed to add as many properties as necessary
  to the configuration element.
-->
<!ELEMENT property EMPTY>
<!ATTLIST property
  name CDATA #REQUIRED
  value CDATA #REQUIRED>

<!--
  The plugin element is used to define a plugin.
-->
<!ELEMENT plugin (property*)>
<!ATTLIST plugin
  type CDATA #REQUIRED>

<!--
  The javaModelGenerator element is used to define properties of the Java Model Generator.
  The Java Model Generator builds primary key classes, record classes, and Query by Example 
  indicator classes.
  This element is deprecated - please use "modelGenerator" instead.
-->
<!ELEMENT javaModelGenerator (property*)>
<!ATTLIST javaModelGenerator
  targetPackage CDATA #REQUIRED
  targetProject CDATA #REQUIRED>

<!--
  The modelGenerator element is used to define properties of the Model Generator (either Java or Kotlin
  can be produced). The Model Generator builds Java model classes, Java records, or Kotlin data classes.
-->
<!ELEMENT modelGenerator (property*)>
<!ATTLIST modelGenerator
  targetPackage CDATA #REQUIRED
  targetProject CDATA #REQUIRED>

<!--
  The javaTypeResolver element is used to define properties of the Java Type Resolver.
  The Java Type Resolver is used to calculate Java types from database column information.
  The default Java Type Resolver attempts to make JDBC DECIMAL and NUMERIC types easier
  to use by substituting Integral types if possible (Long, Integer, Short, etc.)
-->
<!ELEMENT javaTypeResolver (property*)>
<!ATTLIST javaTypeResolver
  type CDATA #IMPLIED>

<!--
  The sqlMapGenerator element is used to define properties of the SQL Map Generator.
  The SQL Map Generator builds an XML file for each table that conforms to MyBatis'
  SQL Mapper DTD.
-->
<!ELEMENT sqlMapGenerator (property*)>
<!ATTLIST sqlMapGenerator
  targetPackage CDATA #REQUIRED
  targetProject CDATA #REQUIRED>

<!--
  The javaClientGenerator element is used to define properties of the Java client Generator.
  The Java Client Generator builds Java interface and implementation classes
  (as required) for each table.
  If this element is missing, then the generator will not build Java Client classes.
  This element is deprecated. Please use "clientGenerator" instead.
-->
<!ELEMENT javaClientGenerator (property*)>
<!ATTLIST javaClientGenerator
  type CDATA #IMPLIED
  targetPackage CDATA #REQUIRED
  targetProject CDATA #REQUIRED>

<!--
  The clientGenerator element is used to define properties of the client Generator.
  The Client Generator builds Java or Kotlin interface and implementation classes
  (as required) for each table.
  If this element is missing, then the generator will not build Client classes.
-->
<!ELEMENT clientGenerator (property*)>
<!ATTLIST clientGenerator
  type CDATA #IMPLIED
  targetPackage CDATA #REQUIRED
  targetProject CDATA #REQUIRED>

<!--
  The table element is used to specify a database table that will be the source information
  for a set of generated objects.
-->
<!ELEMENT table (property*, generatedKey?, domainObjectRenamingRule?, columnRenamingRule?, (columnOverride | ignoreColumn | ignoreColumnsByRegex)*) >
<!ATTLIST table
  catalog CDATA #IMPLIED
  schema CDATA #IMPLIED
  tableName CDATA #REQUIRED
  alias CDATA #IMPLIED
  domainObjectName CDATA #IMPLIED
  mapperName CDATA #IMPLIED
  sqlProviderName CDATA #IMPLIED
  enableInsert CDATA #IMPLIED
  enableSelectByPrimaryKey CDATA #IMPLIED
  enableSelectByExample CDATA #IMPLIED
  enableUpdateByPrimaryKey CDATA #IMPLIED
  enableDeleteByPrimaryKey CDATA #IMPLIED
  enableDeleteByExample CDATA #IMPLIED
  enableCountByExample CDATA #IMPLIED
  enableUpdateByExample CDATA #IMPLIED
  modelType CDATA #IMPLIED
  escapeWildcards CDATA #IMPLIED
  delimitIdentifiers CDATA #IMPLIED
  delimitAllColumns CDATA #IMPLIED>

<!--
  The columnOverride element is used to change certain attributes of the column
  from their default values.
-->
<!ELEMENT columnOverride (property*)>
<!ATTLIST columnOverride
  column CDATA #REQUIRED
  property CDATA #IMPLIED
  javaType CDATA #IMPLIED
  jdbcType CDATA #IMPLIED
  typeHandler CDATA #IMPLIED
  isGeneratedAlways CDATA #IMPLIED
  delimitedColumnName CDATA #IMPLIED>

<!--
  The ignoreColumn element is used to identify a column that should be ignored.
  No generated SQL will refer to the column, and no property will be generated
  for the column in the model objects.
-->
<!ELEMENT ignoreColumn EMPTY>
<!ATTLIST ignoreColumn
  column CDATA #REQUIRED
  delimitedColumnName CDATA #IMPLIED>

<!--
  The ignoreColumnsByRegex element is used to identify a column pattern that should be ignored.
  No generated SQL will refer to the column, and no property will be generated
  for the column in the model objects.
-->
<!ELEMENT ignoreColumnsByRegex (except*)>
<!ATTLIST ignoreColumnsByRegex
  pattern CDATA #REQUIRED>

<!--
  The except element is used to identify an exception to the ignoreColumnsByRegex rule.
  If a column matches the regex rule but also matches the exception, then the
  column will be included in the generated objects.
-->
<!ELEMENT except EMPTY>
<!ATTLIST except
  column CDATA #REQUIRED
  delimitedColumnName CDATA #IMPLIED>

<!--
  The generatedKey element is used to identify a column in the table whose value
  is calculated - either from a sequence (or some other query), or as an identity column.
-->
<!ELEMENT generatedKey EMPTY>
<!ATTLIST generatedKey
  column CDATA #REQUIRED
  sqlStatement CDATA #REQUIRED
  identity CDATA #IMPLIED>

<!--
  The domainObjectRenamingRule element is used to specify a rule for renaming
  object domain name before the corresponding domain object name is calculated
-->
<!ELEMENT domainObjectRenamingRule EMPTY>
<!ATTLIST domainObjectRenamingRule
  searchString CDATA #REQUIRED
  replaceString CDATA #IMPLIED>

<!--
  The columnRenamingRule element is used to specify a rule for renaming
  columns before the corresponding property name is calculated
-->
<!ELEMENT columnRenamingRule EMPTY>
<!ATTLIST columnRenamingRule
  searchString CDATA #REQUIRED
  replaceString CDATA #IMPLIED>

<!--
  The commentGenerator element is used to define properties of the Comment Generator.
  The Comment Generator adds comments to generated elements.
-->
<!ELEMENT commentGenerator (property*)>
<!ATTLIST commentGenerator
  type CDATA #IMPLIED>

=== mybatis/generator/core/mybatis-generator-core/src/test/resources/generatorConfigMyBatis3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2006-2016 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE generatorConfiguration PUBLIC
 "-//mybatis.org//DTD MyBatis Generator Configuration 1.0//EN"
 "http://mybatis.org/dtd/mybatis-generator-config_1_0.dtd">

<generatorConfiguration>
  <!-- This should cause an error because sqlMapGenerator is required
       if there is no javaClientGenerator -->
  <context id="MyBatis3NoClient" targetRuntime="MyBatis3" defaultModelType="flat">
    <plugin type="org.mybatis.generator.plugins.EqualsHashCodePlugin" />

    <jdbcConnection driverClass="org.hsqldb.jdbcDriver"
        connectionURL="jdbc:hsqldb:mem:aname"
        userId="sa" />

    <javaModelGenerator targetPackage="ibatortest.generated.flat.java5.model"
        targetProject="target/generated-sources/mybatis-generator/mybatis3">
      <property name="enableSubPackages" value="true" />
      <property name="trimStrings" value="true" />
    </javaModelGenerator>

    <table tableName="FieldsOnly" />
    <table tableName="PKOnly" />
    <table tableName="PKFields" alias="B" />
    <table tableName="PKBlobs" />
    <table tableName="PKFieldsBlobs" />
    <table tableName="FieldsBlobs" />
    <table tableName="awful table" alias="A">
      <property name="useColumnIndexes" value="true"/>
      <generatedKey column="CuStOmEr iD" sqlStatement="JDBC" />
      <columnOverride column="first name" property="firstFirstName" />
      <columnOverride column="first_name" property="secondFirstName" />
      <columnOverride column="firstName" property="thirdFirstName" />
      <columnOverride column="from" delimitedColumnName="true" >
        <property name="fredswife" value="wilma"/>
      </columnOverride>
      <columnOverride column="active" javaType="boolean" />
    </table>
  </context>

  <!-- This should cause an error because sqlMapGenerator is required
       for the XMLMAPPER client -->
  <context id="MyBatis3XMLMapper" targetRuntime="MyBatis3" defaultModelType="flat">
    <plugin type="org.mybatis.generator.plugins.EqualsHashCodePlugin" />

    <jdbcConnection driverClass="org.hsqldb.jdbcDriver"
        connectionURL="jdbc:hsqldb:mem:aname"
        userId="sa" />

    <javaModelGenerator targetPackage="ibatortest.generated.flat.java5.model"
        targetProject="target/generated-sources/mybatis-generator/mybatis3">
      <property name="enableSubPackages" value="true" />
      <property name="trimStrings" value="true" />
    </javaModelGenerator>
    
    <javaClientGenerator type="XMLMAPPER" targetPackage="ibatortest.generated.flat.java5.client"
     	targetProject="target/generated-sources/mybatis-generator/mybatis3">
    </javaClientGenerator>

    <table tableName="FieldsOnly" />
    <table tableName="PKOnly" />
    <table tableName="PKFields" alias="B" />
    <table tableName="PKBlobs" />
    <table tableName="PKFieldsBlobs" />
    <table tableName="FieldsBlobs" />
    <table tableName="awful table" alias="A">
      <property name="useColumnIndexes" value="true"/>
      <generatedKey column="CuStOmEr iD" sqlStatement="JDBC" />
      <columnOverride column="first name" property="firstFirstName" />
      <columnOverride column="first_name" property="secondFirstName" />
      <columnOverride column="firstName" property="thirdFirstName" />
      <columnOverride column="from" delimitedColumnName="true" >
        <property name="fredswife" value="wilma"/>
      </columnOverride>
      <columnOverride column="active" javaType="boolean" />
    </table>
  </context>

  <!-- This should cause an error because sqlMapGenerator is required
       for the MIXEDMAPPER client -->
  <context id="MyBatis3MixedMapper" targetRuntime="MyBatis3" defaultModelType="flat">
    <plugin type="org.mybatis.generator.plugins.EqualsHashCodePlugin" />

    <jdbcConnection driverClass="org.hsqldb.jdbcDriver"
        connectionURL="jdbc:hsqldb:mem:aname"
        userId="sa" />

    <javaModelGenerator targetPackage="ibatortest.generated.flat.java5.model"
        targetProject="target/generated-sources/mybatis-generator/mybatis3">
      <property name="enableSubPackages" value="true" />
      <property name="trimStrings" value="true" />
    </javaModelGenerator>
    
    <javaClientGenerator type="MIXEDMAPPER" targetPackage="ibatortest.generated.flat.java5.client"
     	targetProject="target/generated-sources/mybatis-generator/mybatis3">
    </javaClientGenerator>

    <table tableName="FieldsOnly" />
    <table tableName="PKOnly" />
    <table tableName="PKFields" alias="B" />
    <table tableName="PKBlobs" />
    <table tableName="PKFieldsBlobs" />
    <table tableName="FieldsBlobs" />
    <table tableName="awful table" alias="A">
      <property name="useColumnIndexes" value="true"/>
      <generatedKey column="CuStOmEr iD" sqlStatement="JDBC" />
      <columnOverride column="first name" property="firstFirstName" />
      <columnOverride column="first_name" property="secondFirstName" />
      <columnOverride column="firstName" property="thirdFirstName" />
      <columnOverride column="from" delimitedColumnName="true" >
        <property name="fredswife" value="wilma"/>
      </columnOverride>
      <columnOverride column="active" javaType="boolean" />
    </table>
  </context>

  <!-- This should not cause an error because sqlMapGenerator is not required
       for the ANNOTATEDMAPPER client -->
  <context id="MyBatis3AnnotatedMapper" targetRuntime="MyBatis3" defaultModelType="flat">
    <plugin type="org.mybatis.generator.plugins.EqualsHashCodePlugin" />

    <jdbcConnection driverClass="org.hsqldb.jdbcDriver"
        connectionURL="jdbc:hsqldb:mem:aname"
        userId="sa" />

    <javaModelGenerator targetPackage="ibatortest.generated.flat.java5.model"
        targetProject="target/generated-sources/mybatis-generator/mybatis3">
      <property name="enableSubPackages" value="true" />
      <property name="trimStrings" value="true" />
    </javaModelGenerator>
    
    <javaClientGenerator type="ANNOTATEDMAPPER" targetPackage="ibatortest.generated.flat.java5.client"
     	targetProject="target/generated-sources/mybatis-generator/mybatis3">
    </javaClientGenerator>

    <table tableName="FieldsOnly" />
    <table tableName="PKOnly" />
    <table tableName="PKFields" alias="B" />
    <table tableName="PKBlobs" />
    <table tableName="PKFieldsBlobs" />
    <table tableName="FieldsBlobs" />
    <table tableName="awful table" alias="A">
      <property name="useColumnIndexes" value="true"/>
      <generatedKey column="CuStOmEr iD" sqlStatement="JDBC" />
      <columnOverride column="first name" property="firstFirstName" />
      <columnOverride column="first_name" property="secondFirstName" />
      <columnOverride column="firstName" property="thirdFirstName" />
      <columnOverride column="from" delimitedColumnName="true" >
        <property name="fredswife" value="wilma"/>
      </columnOverride>
      <columnOverride column="active" javaType="boolean" />
    </table>
  </context>
</generatorConfiguration>

=== mybatis/generator/eclipse/org.mybatis.generator.eclipse.ui.tests/src/org/mybatis/generator/eclipse/ui/content/GoodConfigFile.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--

       Copyright 2006-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.


-->
<!DOCTYPE generatorConfiguration
  PUBLIC "-//mybatis.org//DTD MyBatis Generator Configuration 1.0//EN"
  "http://mybatis.org/dtd/mybatis-generator-config_1_0.dtd" >
<generatorConfiguration>
  <context id="context1" targetRuntime="MyBatis3Simple" >
    <jdbcConnection driverClass="org.hsqldb.jdbcDriver"
      connectionURL="${jdbcUrl}"
      userId="sa" >
    </jdbcConnection>
    <javaModelGenerator targetPackage="gen.model" targetProject="MBGTest" >
        <!--
        <property name="rootClass" value="base.BaseModel" />
        --> 
    </javaModelGenerator>
    <sqlMapGenerator targetPackage="gen.mapper" targetProject="MBGTest" />
    <javaClientGenerator targetPackage="gen.mapper" targetProject="MBGTest" type="XMLMAPPER" />
    <table tableName="a" />
  </context>

  <context id="context2" targetRuntime="MyBatis3Simple" >
    <commentGenerator>
      <property name="suppressAllComments" value="false"/>
    </commentGenerator>
    
    <connectionFactory type="DEFAULT" >
        <property name="driverClass" value="org.hsqldb.jdbcDriver" />
        <property name="connectionURL" value="jdbc:hsqldb:mem:aname" />
        <property name="userId" value="sa" />
    </connectionFactory>
    <javaModelGenerator targetPackage="gen.src.model" targetProject="MBGTest/generatedsrc" />
    <sqlMapGenerator targetPackage="gen.src.mapper" targetProject="MBGTest/generatedsrc" />
    <javaClientGenerator targetPackage="gen.src.mapper" targetProject="MBGTest/generatedsrc" type="XMLMAPPER" />
    <table schema="mbgtest" tableName="%" />
  </context>
</generatorConfiguration>

=== mybatis/generator/jaxbAnnotationsPlugin/jaxbAnnotationsBase/src/test/resources/mbgConfig/MyBatisGeneratorConfig.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
     Copyright 2013-2014 the original author or authors.
 
     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at
 
        http://www.apache.org/licenses/LICENSE-2.0
 
     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
-->

<!--
	Created by Mahiar Mody for testing the Jaxb Annotations Plugin. The MyBatis Generator will read this file
	and generate the MyBatis artefact files containing the Jaxb Annotations.
-->

<!DOCTYPE generatorConfiguration PUBLIC "-//mybatis.org//DTD MyBatis Generator Configuration 1.0//EN" "http://mybatis.org/dtd/mybatis-generator-config_1_0.dtd">
<generatorConfiguration>

	<properties resource="MyBatisGeneratorConfig.properties" />


	<classPathEntry location="${hsql.jdbc.driver.jar.path}" /> <!-- The JDBC driver location. In our case, will be read from the MyBatisGeneratorXml.properties file. -->

	<context id="FieldTypeNoLobs" targetRuntime="MyBatis3" defaultModelType="conditional">

		<plugin type="org.mybatis.generator.plugins.annotations.FieldTypeJaxbAnnotations">
			<property name='UsErs' value='@XmlRootElement(name="usERs")~@XmlAccessorOrder(XmlAccessOrder.ALPHABETICAL)' />
			<property name="UserS.uSer_Id" value="@XmlAttribute" />
			<property name='UserS.first_Name' value='@XmlAttribute(name="first_name",required=true)' />
			<property name='UserPhotos' value='@XmlRootElement(name="Photos",namespace="http://mybatis.generator.org/plugins/jaxb/test")' />
		</plugin>

		<jdbcConnection driverClass="${hsql.driver.class}"
			connectionURL="${hsql.connection.URL}" userId="${hsql.user.id}" password="${hsql.user.password}" />

		<javaModelGenerator targetPackage="fieldType.noLobs.modelDto" targetProject="${targetProject.dir}" />
		<sqlMapGenerator targetPackage="fieldType.noLobs.sqlMaps" targetProject="${targetProject.dir}" />
		<javaClientGenerator targetPackage="fieldType.noLobs.clientDao" targetProject="${targetProject.dir}" type="XMLMAPPER" />

		<table tableName="Users" domainObjectName="Users">
			<generatedKey column="user_id" sqlStatement="CALL IDENTITY();" identity="true" type="post" />
		</table>
		<table tableName="UserSkills" domainObjectName="UserSkills">
			<generatedKey column="skill_id" sqlStatement="CALL IDENTITY();" identity="true" type="post" />
		</table>
		<table tableName="UsersToSkills" domainObjectName="UsersToSkills" />
		<table tableName="UserPhotos" domainObjectName="UserPhotos" />
		<table tableName="UserTutorial" domainObjectName="UserTutorial" />
		<table tableName="UserBlog" domainObjectName="UserBlog" />

	</context>


	<context id="FieldTypeWithLobs" targetRuntime="MyBatis3" defaultModelType="conditional">

		<plugin type="org.mybatis.generator.plugins.annotations.FieldTypeJaxbAnnotations">
			<property name="marshalBlobColumns" value="true" />
			<property name='UsErs' value='@XmlRootElement(name="usERs")~@XmlAccessorOrder(XmlAccessOrder.ALPHABETICAL)' />
			<property name="UserS.uSer_Id" value="@XmlAttribute" />
			<property name='UserS.first_Name' value='@XmlAttribute(name="first_name",required=true)' />
			<property name='UserPhotos' value='@XmlRootElement(name="Photos",namespace="http://mybatis.generator.org/plugins/jaxb/test")' />
		</plugin>

		<jdbcConnection driverClass="${hsql.driver.class}"
			connectionURL="${hsql.connection.URL}" userId="${hsql.user.id}" password="${hsql.user.password}" />

		<javaModelGenerator targetPackage="fieldType.withLobs.modelDto" targetProject="${targetProject.dir}" />
		<sqlMapGenerator targetPackage="fieldType.withLobs.sqlMaps" targetProject="${targetProject.dir}" />
		<javaClientGenerator targetPackage="fieldType.withLobs.clientDao" targetProject="${targetProject.dir}" type="XMLMAPPER" />

		<table tableName="Users" domainObjectName="Users">
			<generatedKey column="user_id" sqlStatement="CALL IDENTITY();" identity="true" type="post" />
		</table>
		<table tableName="UserSkills" domainObjectName="UserSkills">
			<generatedKey column="skill_id" sqlStatement="CALL IDENTITY();" identity="true" type="post" />
		</table>

		<table tableName="UsersToSkills" domainObjectName="UsersToSkills" />
		<table tableName="UserPhotos" domainObjectName="UserPhotos" />
		<table tableName="UserTutorial" domainObjectName="UserTutorial" />
		<table tableName="UserBlog" domainObjectName="UserBlog" />

	</context>


	<context id="PropertyTypeNoLobs" targetRuntime="MyBatis3" defaultModelType="conditional">

		<plugin type="org.mybatis.generator.plugins.annotations.PropertyTypeJaxbAnnotations">
			<property name="marshalBlobColumns" value="false" />
			<property name='UsErs' value='@XmlRootElement(name="usERs")~@XmlAccessorType(XmlAccessType.PROPERTY)' />
			<property name="UserS.uSer_Id" value="@XmlAttribute" />
			<property name='UserS.first_Name' value='@XmlAttribute(name="first_name",required=true)' />
			<property name='UserPhotos' value='@XmlRootElement(name="Photos",namespace="http://mybatis.generator.org/plugins/jaxb/test")' />
		</plugin>

		<jdbcConnection driverClass="${hsql.driver.class}"
			connectionURL="${hsql.connection.URL}" userId="${hsql.user.id}" password="${hsql.user.password}" />

		<javaModelGenerator targetPackage="propertyType.noLobs.modelDto" targetProject="${targetProject.dir}" />
		<sqlMapGenerator targetPackage="propertyType.noLobs.sqlMaps" targetProject="${targetProject.dir}" />
		<javaClientGenerator targetPackage="propertyType.noLobs.clientDao" targetProject="${targetProject.dir}" type="XMLMAPPER" />

		<table tableName="Users" domainObjectName="Users">
			<generatedKey column="user_id" sqlStatement="CALL IDENTITY();" identity="true" type="post" />
		</table>
		<table tableName="UserSkills" domainObjectName="UserSkills">
			<generatedKey column="skill_id" sqlStatement="CALL IDENTITY();" identity="true" type="post" />
		</table>

		<table tableName="UsersToSkills" domainObjectName="UsersToSkills" />
		<table tableName="UserPhotos" domainObjectName="UserPhotos" />
		<table tableName="UserTutorial" domainObjectName="UserTutorial" />
		<table tableName="UserBlog" domainObjectName="UserBlog" />

	</context>


	<context id="PropertyTypeWithLobs" targetRuntime="MyBatis3" defaultModelType="conditional">

		<plugin type="org.mybatis.generator.plugins.annotations.PropertyTypeJaxbAnnotations">
			<property name="marshalBlobColumns" value="true" />
			<property name='UsErs' value='@XmlRootElement(name="usERs")~@XmlAccessorType(XmlAccessType.PROPERTY)' />
			<property name="UserS.uSer_Id" value="@XmlAttribute" />
			<property name='UserS.first_Name' value='@XmlAttribute(name="first_name",required=true)' />
			<property name='UserPhotos' value='@XmlRootElement(name="Photos",namespace="http://mybatis.generator.org/plugins/jaxb/test")' />
		</plugin>

		<jdbcConnection driverClass="${hsql.driver.class}"
			connectionURL="${hsql.connection.URL}" userId="${hsql.user.id}" password="${hsql.user.password}" />

		<javaModelGenerator targetPackage="propertyType.withLobs.modelDto" targetProject="${targetProject.dir}" />
		<sqlMapGenerator targetPackage="propertyType.withLobs.sqlMaps" targetProject="${targetProject.dir}" />
		<javaClientGenerator targetPackage="propertyType.withLobs.clientDao" targetProject="${targetProject.dir}" type="XMLMAPPER" />

		<table tableName="Users" domainObjectName="Users">
			<generatedKey column="user_id" sqlStatement="CALL IDENTITY();" identity="true" type="post" />
		</table>
		<table tableName="UserSkills" domainObjectName="UserSkills">
			<generatedKey column="skill_id" sqlStatement="CALL IDENTITY();" identity="true" type="post" />
		</table>

		<table tableName="UsersToSkills" domainObjectName="UsersToSkills" />
		<table tableName="UserPhotos" domainObjectName="UserPhotos" />
		<table tableName="UserTutorial" domainObjectName="UserTutorial" />
		<table tableName="UserBlog" domainObjectName="UserBlog" />

	</context>

</generatorConfiguration>
